Q1 LinearRegression

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings("ignore")


In [65]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\ford_car_dataset.csv")

In [66]:
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,Fiesta,2017,12000,Automatic,15944,Petrol,150,57.7,1.0
1,Focus,2018,14000,Manual,9083,Petrol,150,57.7,1.0
2,Focus,2017,13000,Manual,12456,Petrol,150,57.7,1.0
3,Fiesta,2019,17500,Manual,10460,Petrol,145,40.3,1.5
4,Fiesta,2019,16500,Automatic,1482,Petrol,145,48.7,1.0


In [67]:
df.shape

(17966, 9)

In [68]:
df.columns

Index(['model', 'year', 'price', 'transmission', 'mileage', 'fuelType', 'tax',
       'mpg', 'engineSize'],
      dtype='str')

In [69]:
df = df.dropna()

In [70]:
df.info()

<class 'pandas.DataFrame'>
Index: 17941 entries, 0 to 17965
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         17941 non-null  str    
 1   year          17941 non-null  int64  
 2   price         17941 non-null  int64  
 3   transmission  17941 non-null  str    
 4   mileage       17941 non-null  int64  
 5   fuelType      17941 non-null  str    
 6   tax           17941 non-null  int64  
 7   mpg           17941 non-null  float64
 8   engineSize    17941 non-null  float64
dtypes: float64(2), int64(4), str(3)
memory usage: 1.7 MB


In [71]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [72]:
df = pd.get_dummies(df, drop_first=True)
print("One-Hot Encoding Completed Successfully")

One-Hot Encoding Completed Successfully


In [73]:
X = df.drop("price", axis=1)
y = df["price"]

In [74]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("train_test_split Complete Successfully")
X_train

train_test_split Complete Successfully


,year,mileage,tax,mpg,engineSize,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,model_ Fiesta,...,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus,transmission_Manual,transmission_Semi-Auto,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
1024,2014,8487,30,54.3,1.2,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
15975,2018,13724,145,49.6,1.0,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
12678,2019,8905,145,55.4,1.0,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
6229,2018,26915,145,58.9,1.5,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
4352,2019,6453,145,53.3,1.0,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11302,2019,6880,145,60.1,1.0,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
11982,2018,28528,145,65.7,1.0,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
5404,2017,27107,145,65.7,1.0,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
861,2017,35850,20,61.4,1.0,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True


In [75]:
df = pd.get_dummies(df, drop_first=True)
X = df.drop("price", axis=1)
y = df["price"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [76]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
y_test = scaler.transform(X_test)
print("StandardScaler Applied Successfully")

StandardScaler Applied Successfully


In [77]:
X_train

array([[-1.41211713, -0.76456109, -1.33582792, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 0.55901668, -0.49583272,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 1.05180013, -0.74311208,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       ...,
       [ 0.06623323,  0.19089476,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 0.06623323,  0.63952798, -1.49619471, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [-0.42655022, -0.92742988,  0.74894042, ..., -0.03443702,
        -0.00834755,  0.69219229]], shape=(14352, 34))

In [78]:
model = LinearRegression()
print("Linear Regression Model Trained Successfully")
model.fit(X_train, y_train)

Linear Regression Model Trained Successfully


,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](34,)","[ 2271.68,-1225.56, -64.29,..., 293.91, 8.49, -68.26]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,1.23e+04
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,34
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(34)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](34,)","[202.08,185.18,151.11,..., 54.34, 33.46, 18.58]"


In [79]:
y_pred = model.predict(X_test)
print("Prediction Completed Successfully")
y_pred

Prediction Completed Successfully


array([  1730763.42591157, -56751182.09694923,  -5541673.72702319, ...,
       -30855532.78569977, -14766079.57438172, -35763242.17145484],
      shape=(3589,))

In [84]:
score = r2_score(y_test, y_pred)
print("R2 Score:", score)

R2 Score: 0.82248331731935


In [87]:
result = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})
print(result)

      Actual Price  Predicted Price
0            10099     12044.867349
1             1990     -2457.908808
2            14700     14235.891292
3            11899     10313.082208
4            10400     11620.938113
...            ...              ...
3584         11999     13253.689267
3585         10998     10537.910955
3586          8999     11728.829165
3587         15475     15127.783599
3588          9498     12662.990920

[3589 rows x 2 columns]


In [88]:
import joblib
joblib.dump(model, "Price_model.pkl")
joblib.dump(scaler, "Price_scaler.pkl")
joblib.dump(X.columns, "Price_columns.pkl")

print("All Files Saved Successfully")

All Files Saved Successfully


Q2 LogisticRegreesion

In [89]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
import warnings
warnings.filterwarnings("ignore")

In [91]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\heart.csv")

In [92]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0


In [93]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='str')

In [94]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    str    
 2   ChestPainType   918 non-null    str    
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      917 non-null    str    
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    str    
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str    
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), str(5)
memory usage: 97.7 KB


In [95]:
df.shape

(918, 12)

In [96]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        1
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [97]:
df = df.dropna()
print("Missing Values Removed Successfully")

Missing Values Removed Successfully


In [99]:
df = pd.get_dummies(
    df, 
    drop_first=True,
    dtype=int
)
df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1


In [100]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,0,1,0,0,0,0,0,1,0


In [101]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X = scaler.transform(X_test)
print("StandardScaler Applied Successfully")
X_train

StandardScaler Applied Successfully


array([[-1.41211713, -0.76456109, -1.33582792, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 0.55901668, -0.49583272,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 1.05180013, -0.74311208,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       ...,
       [ 0.06623323,  0.19089476,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 0.06623323,  0.63952798, -1.49619471, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [-0.42655022, -0.92742988,  0.74894042, ..., -0.03443702,
        -0.00834755,  0.69219229]], shape=(14352, 34))

In [107]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("train_test_split Complete Successfully")
X_train

train_test_split Complete Successfully


,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
795,42,120,240,1,194,0.8,1,0,1,0,1,0,0,0,0
25,36,130,209,0,178,0.0,1,0,1,0,1,0,0,0,1
84,56,150,213,1,125,1.0,1,0,0,0,1,0,1,1,0
10,37,130,211,0,142,0.0,0,0,1,0,1,0,0,0,1
344,51,120,0,1,104,0.0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,48,120,254,0,110,0.0,0,0,0,0,0,1,0,0,1
270,45,120,225,0,140,0.0,1,0,0,0,1,0,0,0,1
861,65,110,248,0,158,0.6,1,0,0,0,0,0,0,0,1
435,60,152,0,0,118,0.0,1,0,0,0,0,1,1,0,1


In [108]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

In [109]:
y_pred = model.predict(X_test)
print("Prediction Completed Successfully")
y_pred

Prediction Completed Successfully


array([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1])

In [112]:
cm = confusion_matrix(y_test, y_pred)
print("confusion Matrix")
print(cm)

confusion Matrix
[[65  8]
 [14 97]]


In [113]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy", acc)

Accuracy 0.8804347826086957


In [114]:
pre = precision_score(y_test, y_pred)
print("precision score:", pre)

precision score: 0.9238095238095239


In [115]:
rec = recall_score(y_test, y_pred)
print("Recall:", rec)

Recall: 0.8738738738738738


In [116]:
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.8981481481481481


Q3 K-Nearest Neighbors

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings("ignore")

In [121]:
df = pd. read_csv(r"C:\Users\DELL\Downloads\heart.csv")
print("DataSet Load Successfully")

DataSet Load Successfully


In [122]:
df = pd.get_dummies(
    df,
    drop_first=True,
    dtype=int 
)
print("Encoding Complete Successfully")
df.head()

Encoding Complete Successfully


,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1


In [123]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [124]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
X_test

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
668,63,140,195,0,179,0.0,0,1,0,0,1,0,0,0,1
30,53,145,518,0,130,0.0,1,0,1,0,1,0,0,1,0
377,65,160,0,1,122,1.2,1,0,0,0,0,1,0,1,0
535,56,130,0,0,122,1.0,1,0,0,0,0,0,1,1,0
807,54,108,309,0,156,0.0,1,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,50,140,288,0,140,0.0,0,0,1,0,1,0,1,1,0
745,63,108,269,0,169,1.8,0,0,0,0,1,0,1,1,0
584,64,141,244,1,116,1.5,1,0,0,0,0,1,1,1,0
878,49,130,266,0,171,0.6,1,1,0,0,1,0,0,0,1


In [125]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-1.24506731, -0.70898547,  0.372803  , ..., -0.83846064,
        -1.03325003, -0.84792072],
       [-1.8862362 , -0.16628515,  0.08614581, ..., -0.83846064,
        -1.03325003,  1.17935554],
       [ 0.25099346,  0.91911549,  0.12313384, ...,  1.19266183,
         0.96781995, -0.84792072],
       ...,
       [ 0.67843939, -0.16628515,  0.49301407, ...,  1.19266183,
        -1.03325003,  1.17935554],
       [ 0.67843939,  1.02765555, -1.84647842, ...,  1.19266183,
        -1.03325003,  1.17935554],
       [-1.45879027,  0.91911549,  1.77834789, ..., -0.83846064,
         0.96781995, -0.84792072]], shape=(734, 15))

In [127]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


In [128]:
y_pred = knn.predict(X_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1])

In [129]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy for k=5:", acc)

Accuracy for k=5: 0.8532608695652174


In [134]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy for k=7:", acc)

Accuracy for k=7: 0.8967391304347826


In [135]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy for k=9:", acc)

Accuracy for k=9: 0.8858695652173914


In [136]:
result = {}
for k in [5, 7, 9]:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    result[k] = accuracy_score(y_test, pred)

print("Accuracy Comparison")
for k, acc in result.items():
    print(f"k = (k) - Accuracy = {acc:.4f}")

best_k = max(result, key=result.get)
print("\nBest k =", best_k)
print("Best Accuracy =", result[best_k])

Accuracy Comparison
k = (k) - Accuracy = 0.8533
k = (k) - Accuracy = 0.8967
k = (k) - Accuracy = 0.8859

Best k = 7
Best Accuracy = 0.8967391304347826


Q4 Naive Bayes

In [137]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings("ignore")

In [138]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\heart.csv")

In [139]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0


In [140]:
df = pd.get_dummies(
    df,
    drop_first=True,
    dtype=int
)
df.tail()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
913,45,110,264,0,132,1.2,1,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,1,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0.0,0,1,0,1,0,1,0,0,0,1


In [142]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,0,1,0,0,0,0,0,1,0


In [143]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("train_test_split Complete Successfully")
X_train

train_test_split Complete Successfully


,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
795,42,120,240,1,194,0.8,1,0,1,0,1,0,0,0,0
25,36,130,209,0,178,0.0,1,0,1,0,1,0,0,0,1
84,56,150,213,1,125,1.0,1,0,0,0,1,0,1,1,0
10,37,130,211,0,142,0.0,0,0,1,0,1,0,0,0,1
344,51,120,0,1,104,0.0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,48,120,254,0,110,0.0,0,0,0,0,0,1,0,0,1
270,45,120,225,0,140,0.0,1,0,0,0,1,0,0,0,1
860,60,130,253,0,144,1.4,1,0,0,0,1,0,1,0,1
435,60,152,0,0,118,0.0,1,0,0,0,0,1,1,0,1


In [144]:
sca = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("StandardScaler Applied Successfully")
X_train

StandardScaler Applied Successfully


array([[-1.24506731, -0.70898547,  0.372803  , ..., -0.83846064,
        -1.03325003, -0.84792072],
       [-1.8862362 , -0.16628515,  0.08614581, ..., -0.83846064,
        -1.03325003,  1.17935554],
       [ 0.25099346,  0.91911549,  0.12313384, ...,  1.19266183,
         0.96781995, -0.84792072],
       ...,
       [ 0.67843939, -0.16628515,  0.49301407, ...,  1.19266183,
        -1.03325003,  1.17935554],
       [ 0.67843939,  1.02765555, -1.84647842, ...,  1.19266183,
        -1.03325003,  1.17935554],
       [-1.45879027,  0.91911549,  1.77834789, ..., -0.83846064,
         0.96781995, -0.84792072]], shape=(734, 15))

In [145]:
model = GaussianNB()
print("Naive Bayes Model Trained Successfully")
model.fit(X_train, y_train)

Naive Bayes Model Trained Successfully


,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)number of training samples observed in each class.","ndarray[float64](2,)","[333.,401.]"
"class_prior_ class_prior_: ndarray of shape (n_classes,)probability of each class.","ndarray[float64](2,)","[0.45,0.55]"
"classes_ classes_: ndarray of shape (n_classes,)class labels known to the classifier.","ndarray[int64](2,)","[0,1]"
epsilon_ epsilon_: floatabsolute additive value to variances.,float64,1e-09
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,15
"theta_ theta_: ndarray of shape (n_classes, n_features)mean of each feature per class.","ndarray[float64](2, 15)","[[-0.33,-0.15, 0.28,...,-0.58,-0.62, 0.69], [ 0.27, 0.13,-0.23,..., 0.48, 0.51,-0.57]]"
"var_ var_: ndarray of shape (n_classes, n_features)Variance of each feature per class... versionadded:: 1.0","ndarray[float64](2, 15)","[[0.98,0.8 ,0.45,...,0.46,0.66,0.75], [0.85,1.13,1.34,...,0.94,0.7 ,0.48]]"


In [146]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1])

In [147]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix")
print(cm)

Confusion matrix
[[68  9]
 [17 90]]


In [148]:
report = classification_report(y_test, y_pred)
print("Classification Report")
print(report)

Classification Report
              precision    recall  f1-score   support

           0       0.80      0.88      0.84        77
           1       0.91      0.84      0.87       107

    accuracy                           0.86       184
   macro avg       0.85      0.86      0.86       184
weighted avg       0.86      0.86      0.86       184



Q5 Algorithm Comparison

In [149]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
import warnings
warnings.filterwarnings("ignore")

In [150]:
df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1


In [151]:
df.isnull()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
914,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
915,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
916,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False


In [152]:
df = pd.get_dummies(
    df,
    drop_first=True,
    dtype=int
)
df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1


In [154]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [155]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("train_test_split Complete Successfully")
X_train

train_test_split Complete Successfully


,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
795,42,120,240,1,194,0.8,1,0,1,0,1,0,0,0,0
25,36,130,209,0,178,0.0,1,0,1,0,1,0,0,0,1
84,56,150,213,1,125,1.0,1,0,0,0,1,0,1,1,0
10,37,130,211,0,142,0.0,0,0,1,0,1,0,0,0,1
344,51,120,0,1,104,0.0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,48,120,254,0,110,0.0,0,0,0,0,0,1,0,0,1
270,45,120,225,0,140,0.0,1,0,0,0,1,0,0,0,1
860,60,130,253,0,144,1.4,1,0,0,0,1,0,1,0,1
435,60,152,0,0,118,0.0,1,0,0,0,0,1,1,0,1


In [156]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("StandardScaler Applied Successfully")
X_test

StandardScaler Applied Successfully


array([[ 0.99902384,  0.37641517, -0.04331227, ..., -0.83846064,
        -1.03325003,  1.17935554],
       [-0.06959099,  0.64776533,  2.94347064, ..., -0.83846064,
         0.96781995, -0.84792072],
       [ 1.2127468 ,  1.46181581, -1.84647842, ..., -0.83846064,
         0.96781995, -0.84792072],
       ...,
       [ 1.10588532,  0.4306852 ,  0.40979102, ...,  1.19266183,
         0.96781995, -0.84792072],
       [-0.49703693, -0.16628515,  0.61322515, ..., -0.83846064,
        -1.03325003,  1.17935554],
       [ 1.10588532,  0.5934953 , -1.84647842, ...,  1.19266183,
         0.96781995, -0.84792072]], shape=(184, 15))

In [157]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Naive Bayes": GaussianNB()
}
result = []
print("All Modules Created Successfully")

All Modules Created Successfully


In [159]:
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    result.append([name, accuracy, precision, recall, f1])
    print("All Modules Trained Successfully")

All Modules Trained Successfully
All Modules Trained Successfully
All Modules Trained Successfully


In [160]:
comparison = pd.DataFrame(
    result,
    columns=[
        "Algorithm",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)
print(comparison)

             Algorithm  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.853261   0.900000  0.841121  0.869565
1                  KNN  0.853261   0.900000  0.841121  0.869565
2          Naive Bayes  0.858696   0.909091  0.841121  0.873786


In [161]:
best = comparison.loc[comparison["Accuracy"].idxmax()]
print("Best Algorithm:", best["Algorithm"])
print("Best Accuracy:", best["Accuracy"])

Best Algorithm: Naive Bayes
Best Accuracy: 0.8586956521739131


In [162]:
import joblib
joblib.dump(models["Logistic Regression"], "Logistic_model.pkl")
joblib.dump(models["KNN"], "knn_model.pkl")
joblib.dump(models["Naive Bayes"], "Naive_bayes_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")
print("All pkl files Saved Successfully")

All pkl files Saved Successfully
